yoshisuga/MAME4iOS

iOS/EmulatorController.h, iOS/EmulatorController.m
Hi,
I've added haptic feedback which makes using the on screen dpad and buttons closer to real buttons
=> added haptic feedback

iOS-res/Applications/MAME4iOS.app/SKIN_1/controller_landscape_full_iPhone_6.txt
Switch X and A buttons and fixed the position of the Digital DPAD for iPhone 6/7/8 full landscape.
=> Switch X and A buttons and fixed Digital DPAD

iOS/EmulatorController.m
when upload rom file, restart the app, it move rom file to roms , will crash because  some wrong happen about progressAlert.
=> fix the crash when move roms file

iOS/EmulatorController.h, iOS/EmulatorController.m, iOS/OptionsController.h, iOS/OptionsController.m, xcode/MAME4iOS/Alert.m, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/TVOptionsController.h, xcode/MAME4iOS/TVOptionsController.m
added "Start Server" to Settings (iOS and tvOS)
added "Import" to Settings. (iOS only)
added "Export" to Settings. (iOS only)
removed "Start Server" from in-game menu, need to access from Settings.
Added support for context menu on tvOS
=> remove rom filter options from Settings (iOS and tvOS)

iOS/EmulatorController.m, iOS/OptionsController.h
smarter ZIP import, handle ROM files with spaces, ie "gamename (1).zip" ==> "game name.zip"
=> move "IMPORT and EXPORT" to the top of Settings.

iOS/EmulatorController.m, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/MAME4iOS/MAME4iOS-Info.plist
...this prevents us showing a toast, or doing other dumb things.
=> touch controls are always off on tvOS

xcode/MAME4iOS/ChooseGameController.m
show more info in small view mode.
=> show full info in context menu.

iOS/EmulatorController.m, iOS/OptionsController.m, xcode/MAME4iOS/Alert.h, xcode/MAME4iOS/Alert.m, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/FileItemProvider.h, xcode/MAME4iOS/FileItemProvider.m, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj, xcode/MAME4iOS/ZipFile.h, xcode/MAME4iOS/ZipFile.m
Support exporting all game ROMs as a ZIP via UIActivityViewController
=> Export zip

iOS/EmulatorController.m
don't save current game until we enter the background.
=> fix crash loop on missing CHD.

iOS/EmulatorController.h, iOS/EmulatorController.m, xcode/MAME4iOS/FileItemProvider.m
* on first launch (or no-roms) offer to Start Server **or** Import ROMs with a document picker
* show the MAME logo when ever we are not running a game.
* fix progress dialog during an export....
=> OBE, export, show logo

iOS/EmulatorController.m, xcode/MAME4iOS/ZipFile.h, xcode/MAME4iOS/ZipFile.m
expanding the full rom set is now ~6min (down from 10min)
=> a few more ZIP tweaks.

iOS-res/Applications/MAME4iOS.app/help.md, iOS-res/Applications/MAME4iOS.app/whatsnew.md, iOS/AnalogStick.m, iOS/EmulatorController.h, iOS/EmulatorController.m, iOS/Globals.h, iOS/ScreenView.h, iOS/ScreenView.m, iOS/iCadeView.m, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osd-ios.c, src/osd/droid-ios/osdinput.c, xcode/MAME4iOS/Alert.m
do some fixes and enhancements to make 1UP and 2UP games easier to start, and make sure multiple game controllers work smoothly.
look at the commit messages for TMI.
=> Ready Player Two

xcode/MAME4iOS/ChooseGameController.m
* title of delete confirmation is full metadata.
* Delete All Settings, will now delete everything *except* the `ROMSET`
* Delete Everything will also delete the `ROMSET`
=> Issue #180 and #181

iOS/EmulatorController.m
* check for bluetooth not authorized, and don't make any bluetooth calls until we are in a known state.
* moveROMs very broken on first boot.
=> Real fix for tvOS first boot.

iOS/CGScreenView.m, iOS/EmulatorController.h, iOS/EmulatorController.m, iOS/MetalScreenView.h, iOS/MetalScreenView.m, iOS/OptionsController.m, iOS/ScreenView.h, xcode/MAME4iOS/ChooseGameController.h, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj, xcode/MAME4iOS/PopupSegmentedControl.h, xcode/MAME4iOS/PopupSegmentedControl.m, xcode/MAME4iOS/TVOptionsController.m
- Added a native FPS counter.
- Removed display of the MAME frame rate.
- Added more scaffolding for Metal.
- PopupSegmentedControl update.
=> Replace MAME frame rate with a native one, and preparing the way for Metal🤘

iOS/MetalScreenView.m, xcode/MAME4iOS/MameShaders.metal, xcode/MAME4iOS/MetalView.m
=> added CLAMP TO ZERO as default texture address mode.

iOS-res/Applications/MAME4iOS.app/whatsnew.md, iOS/EmulatorController.m, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osd-ios.c, src/osd/droid-ios/osdinput.c, xcode/MAME4iOS/InfoHUD.h, xcode/MAME4iOS/InfoHUD.m
....also added a RESET (MAME soft reset option) to the HUD.
=> P3 and P4 - Start options for P3, P4 in in-game menu and HUD

iOS/EmulatorController.m, iOS/MetalScreenView.m, xcode/MAME4iOS/MameShaders.metal, xcode/MAME4iOS/MetalView.m
added a line shader that fades out lines from the past.
don't show the timecode.
=> LINE FADE SHADER

iOS/EmulatorController.m, xcode/MAME4iOS/ChooseGameController.m
=> save position of the HUD for landscape and portrait

iOS/EmulatorController.m
=> fix for web-server on iOS 14

README.md, WHATSNEW.md, xcode/MAME4iOS/MAME4iOS.xcconfig, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj, xcode/MAME4iOS/MAME4iOS.xcodeproj/xcshareddata/xcschemes/MAME tvOS Debug.xcscheme, xcode/MAME4iOS/MAME4iOS.xcodeproj/xcshareddata/xcschemes/MAME tvOS Release.xcscheme
move TEAM ID, ORG IDENTIFIER, and VERSION out of the project file and into `MAME4iOS.xcconfig`
```
ORG_IDENTIFIER = com.example    // CHANGE this to your Organization Identifier.
ORG_TEAM       = ABC8675309     // CHANGE this to your Team ID.
APP_VERSION    = 2020.13        // Version of all Targets.
APP_BUILD      = 2020.13        // Build of all Targets.
```
=> Use XCCONFIG for global project settings. 

xcode/MAME4iOS/ChooseGameController.m
fix issue #260
and tweak the select UI
=> tvOS select issue, and UI tweak.

iOS/EmulatorController.m, src/emu/video.c, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osd-ios.c, src/osd/droid-ios/osdinput.c, xcode/MAME4iOS/UIView+Toast.h, xcode/MAME4iOS/UIView+Toast.m
* Capture MAME WARNING and ERROR output
* show it to the user if the game fails to run.
* add option to in-game menu to display warning/error text.
* Issue #264
=> MAME WARNING and ERROR

WHATSNEW.md, iOS/Bootstrapper.m, makefile, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/MAME4iOS.xcconfig, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj, xcode/MAME4iOS/MAME4mac/MAME4mac.sandbox.entitlements
use `MAME4mac.sandbox.entitlements` for a non-icloud enabled build
Fix for #267
=> fix for MacApp not being sandboxed 

iOS-res/help.md, iOS/Bootstrapper.m, iOS/EmulatorController.m, iOS/Globals.h, iOS/InputOptionController.m, iOS/ListOptionController.h, iOS/ListOptionController.m, iOS/NetplayController.m, iOS/OptionsController.h, iOS/OptionsController.m, iOS/iCadeView.h, iOS/iCadeView.m, src/emu/uimenu.c, src/emu/video.c, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osd-ios.c, src/osd/droid-ios/osdinput.c, src/osd/droid-ios/osdmain.c, xcode/MAME4iOS/Options.h, xcode/MAME4iOS/Options.m, xcode/MAME4iOS/SystemImage.m, xcode/MAME4iOS/TVInputOptionsController.m, xcode/MAME4iOS/TVOptionsController.h, xcode/MAME4iOS/TVOptionsController.m
do some settings and globals gardening (mostly pruning)
remove from the Settings UI old settings that are not needed anymore, also if possible remove the myosd global too.
=> Settings Gardening

iOS-res/help.md, iOS/Bootstrapper.m, iOS/EmulatorController.h, iOS/EmulatorController.m, iOS/Globals.h, iOS/InputOptionController.m, iOS/ListOptionController.h, iOS/ListOptionController.m, iOS/NetplayController.m, iOS/OptionsController.h, iOS/OptionsController.m, iOS/iCadeView.h, iOS/iCadeView.m, src/emu/uimenu.c, src/emu/video.c, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osd-ios.c, src/osd/droid-ios/osdinput.c, src/osd/droid-ios/osdmain.c, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/MAME4iOS/MAME4iOS-Info.plist, xcode/MAME4iOS/MAME4mac/MAME4mac-Info.plist, xcode/MAME4iOS/MAME4tvOS/Info.plist, xcode/MAME4iOS/Options.h, xcode/MAME4iOS/Options.m, xcode/MAME4iOS/SystemImage.m, xcode/MAME4iOS/TVInputOptionsController.m, xcode/MAME4iOS/TVOptionsController.h, xcode/MAME4iOS/TVOptionsController.m
- left mouse button is A/BUTTON1, right is B/BUTTON2, and middle is Y/BUTTON3
- supports mouse scroll wheel as the Z Axis
- player can either use current touch screen mouse/lightgun or hardware mouse/trackpad, they both work at the same time.
- on macOS direct mouse input is only used when window is fullscreen.
**NOTE** this PR builds on #292
=> Mouse Input

src/mame/machine/stvprot.c
Fixed Tecmo World Cup '98 (player movement) issue.
=> updated stvprot.c

make-ios.sh, make-sim.sh, make-tvos-sim.sh, make-tvos.sh, makefile
Dont run Xcode if `make-ios.sh` fails to build `libmame` so the user will notice the error
=> check for error(s) in build script, and stop (dont run Xcode)

xcode/MAME4iOS/ChooseGameController.m
=> limit title to 3 lines, and tweak the font size on tvOS

iOS/EmulatorController.m, iOS/Globals.h, src/emu/inptport.c, src/emu/uimenu.c, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osdinput.c
detect 2,4,8 ways, *exactly* like we did before....
=> fix 8-way joystick detection

README.md, TODO.md, iOS/EmulatorController.m, iOS/Globals.h, iOS/KeyboardView.m, src/emu/uimenu.c, src/osd/droid-ios/libmame.h, src/osd/droid-ios/myosd.h, src/osd/droid-ios/osdinput.c, src/osd/droid-ios/osdmain.c, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/GameInfo.h, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj, xcode/MAME4iOS/MetalView.m, xcode/MAME4iOS/SoftwareList.m
* added blurb about SoftwareLists in README.md
* added TODO.md to the project
* remove *fake* game data now that OSD gives us the game_list
=> Modern mame

xcode/MAME4iOS/ChooseGameController.m
put a badge on favorite games.
=> Badges! we need some stink'n badges!

README.md, WHATSNEW.md, get-libmame.sh, howtobuild.txt, make-ios.sh, make-mac.sh, make-sim.sh, make-tvos-sim.sh, make-tvos.sh, makefile, xcode/MAME4iOS/MAME4iOS.xcconfig, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
build LIBMAME from the Xcode project, running a script from `Terminal.app` not required anymore
=> Xcode build

.gitignore, xcode/MAME4iOS/MAME4iOS.xcconfig, xcode/MAME4iOS/build-release-ipas.sh
Use a local non-git tracked settings file `xcode/MAME4iOS/Developer.xcconfig`
=> non git tracked Developer.xcconfig

iOS/Bootstrapper.m, xcode/MAME4iOS/GameInfo.h, xcode/MAME4iOS/GameInfo.m, xcode/MAME4iOS/TopShelf/ContentProvider.m, xcode/MAME4iOS/TopShelf/Info.plist
* support items with multiple images (ie all of them...)
* open a MESS style url correctly
=> clean up TopShelf

xcode/MAME4iOS/TVAlertController.swift
Catalyst version needed a few tweaks related to the min/max of the screen.....
and use a larger (tvOS style) font
=> UX Tweaks for macCatalyst

WHATSNEW.md, iOS/EmulatorController.m, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/GameInfo.h, xcode/MAME4iOS/GameInfo.m, xcode/MAME4iOS/SoftwareList.h, xcode/MAME4iOS/SoftwareList.m
build a dynamic argc, argv in run_mame
added a new key kGameInfoCustomCmdline to GameInfo
=> Support custom command line options passed to MAME

xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/CommandLineArgsHelper.swift, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
Added the command line args helper swift file to the tvOS target, added conditional compiling for tvOS around UIPasteboard and some font and color api issues.
=> Fix building for tvOS

xcode/MAME4iOS/ChooseGameController.m
* don't load files in `software` on MAME 139
* handle files with `UPPERCASE` file extensions.
* Show Info keys alphabetical.
* don't crash with bad IndexPath on tvOS with empty section.
* use a small `star` for favorite.
=> a few minor bug fixes.

iOS/EmulatorController.m, src/osd/droid-ios/osdinput.c
This lets games like TERM2 use a mouse (touch or hardware)
=> do a better job detecting mouse input for the current MAME machine.

iOS/MetalScreenView.m
this was causing some problems on ProMotion displays
=> don't limit the MetalView frame rate

xcode/MAME4iOS/TVAlertController.swift
use a UISwitch in the HUD if the param is binary (ie only 0.0 and 1.0 allowed), only on iOS
=> use a UISwitch in the HUD

WHATSNEW.md, iOS/MetalScreenView.m, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
Use the Accelerate vImage framework to convert YcRcB
=> Support the YUV16 texture format, used for LD games (ie firefox etc)

iOS/Bootstrapper.m, iOS/Globals.h, xcode/MAME4iOS/ChooseGameController.h, xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/GameInfoController.swift, xcode/MAME4iOS/InfoDatabase.h, xcode/MAME4iOS/InfoDatabase.m, xcode/MAME4iOS/MAME4iOS-Bridging-Header.h, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
* Convert `GameInfoController` to Swift
* small step toward more Swift code.
* `ChooseGameControler` and `GameInfo` next
=> Convert more code to Swift

xcode/MAME4iOS/ChooseGameController.m, xcode/MAME4iOS/GameInfoController.swift
Make `game` property a non-optional, fix initializer and some minor cleanup.
=> GameInfoController fixes

iOS/Bootstrapper.m, xcode/MAME4iOS/CloudSync.m, xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj, xcode/MAME4iOS/TVAlertController.swift
* fix UX glitch with popover placement.
* Check if iCloud Entitlement exists before calling any iCloud API.
* fix Audio silence
=> Fixes for iOS 16

iOS/EmulatorController.m, xcode/MAME4iOS/ChooseGameController.m
choose the first media kind that supports file type.
this way we will choose `flop1` *not* `flop4`
=> choose `flop1` *not* `flop4`

xcode/MAME4iOS/build-release-ipas.sh
use shell script mumbo jumbo to get the version of the MAMELIB
=> Use MAMELIB version in IPA name
