- makefile
dummy variable to hold -w in case you want to use it to clean up the warnings.
> suppress warnings placeholder

- iOS/EmulatorController.m
Loading a new landscape background image for iPhone6/7/8
The image called "back_landscape_iPhone_6.png"is a duplicate of the "back_landscape_iPhone_5.png" already present in the folder.
> New background image for landscape no-full view.

- iOS-res/Applications/MAME4iOS.app/SKIN_1/controller_portrait_iPhone_6.txt
Switch X and A buttons and fixed the position of the Digital DPAD for iPhone 6/7/8 non full portrait.
> Switch X and A buttons and fixed Digital DPAD

- iOS/EmulatorController.m
- xcode/MAME4iOS/ChooseGameController.m
- xcode/MAME4iOS/ZipFile.m
changed what the context menu Share... does
instead of just sharing ROMNAME.zip, it shares all files including artwork, saved state, and hiscores. 
it puts all the files in a single zip called "Short Description (romname).zip" for example "Donkey Kong (dkong).zip"
when you re-import this zip, you will get back *everything*
also fixed a ZipFile reading bug. (a zip in a zip  near end, would cause a problem!)
> export a game and all of its state (hiscores, saved state, artwork, etc)

- iOS/Bootstrapper.m
- iOS/EmulatorController.m
you can now use MENU+🅧 to exit MAME menu, MAME UI, or cancel an input assign.
> MENU+🅧 on controller is always EXIT, not just Exit Game.

- iOS-res/Applications/MAME4iOS.app/whatsnew.md
- iOS/OptionsController.m
- iOS/ScreenView.m
- src/osd/droid-ios/osd-droid.c
- src/osd/droid-ios/osd-ios.c
- src/osd/droid-ios/osdvideo.c
- xcode/MAME4iOS/TVOptionsController.m
This PR adds support for rendering MAME at a resolution higher than 1024x768 all the way up to UHD/4K.
- Rendering at a higher resolution definitely improves the MAME Artwork experience inside the app. 
- New resolutions supported: 1280x960, 1440x1080(Optimal HD: added for 1080P displays), 1600x1200, 1920x1440, 2048x1536, 2880x2160(Optimal UHD: added for 2160P displays)
> Add support for 4K/UHD and other render resolutions

- iOS-res/Applications/MAME4iOS.app/whatsnew.md
- iOS/CGScreenView.h
- iOS/CGScreenView.m
- iOS/EmulatorController.h
- iOS/EmulatorController.m
- iOS/OptionsController.m
- iOS/ScreenView.h
- iOS/iCadeView.m
- src/osd/droid-ios/myosd.h
- src/osd/droid-ios/osd-ios.c
- src/osd/droid-ios/osdinput.c
- src/osd/droid-ios/osdsound.c
- src/osd/droid-ios/osdvideo.c
- xcode/MAME4iOS/TVOptionsController.m
This change does a few things.
* Overlay effects (CRT, Scanline, ...)
- Works correctly when using artwork, effect will only overlay the game screen, not the bezels.
- effect now handles the pixel/scanline size correctly when scaled.
- Multiple screens (like cocktail layouts) will get overlay effects right.
- Vector games will not get effects.
* Default Artwork size.
- Artwork is shown at optimal size when `Emulated Resolution` is set to `Auto` (the default)
* OSD layer
- new "call up" myosd_video_draw and iphone_DrawScreen
> HiRes MAME Artwork

- iOS/EmulatorController.m
- iOS/HelpController.h
- iOS/HelpController.m
- iOS/LayoutData.h
- iOS/LayoutData.m
- xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
- xcode/MAME4iOS/MAME4iOS.xcodeproj/xcshareddata/xcschemes/MAME tvOS Debug.xcscheme
- xcode/MAME4iOS/MAME4iOS.xcodeproj/xcshareddata/xcschemes/MAME tvOS Release.xcscheme
- xcode/MAME4iOS/MAME4iOS.xcodeproj/xcshareddata/xcschemes/MAME4iOS 64-bit Debug.xcscheme
- xcode/MAME4iOS/MAME4iOS.xcodeproj/xcshareddata/xcschemes/MAME4iOS 64-bit Release.xcscheme
- xcode/MAME4iOS/MetalView.m
changed deployment target from iOS 11 -> iOS 12
changed use of MobileCoreServices to CoreServices.
UIWebView deprecated, converted to  WKWebView.
NSKeyedArchiver deprecation.
NOTE in order to Use CoreServices I had to up the deployment target to iOS 12.
ALSO added a call to updateOptions before we fire up the MAME thread, so key globals will be in a know state when the myosd audio system initializes.
> Build clean on Xcode 12

- iOS-res/Applications/MAME4iOS.app/help.md
- iOS-res/Applications/MAME4iOS.app/whatsnew.md
- iOS/EmulatorController.m
- xcode/MAME4iOS/ChooseGameController.m
- xcode/MAME4iOS/SteamController/SteamController.h
- xcode/MAME4iOS/SteamController/SteamController.m
- xcode/MAME4iOS/SteamController/SteamControllerExtendedGamepad.h
- xcode/MAME4iOS/SteamController/SteamControllerExtendedGamepad.m
iOS 14 gives us access to the `MENU` (aka `GUIDE` on Xbox, and `PS` button on DualShock)  
this PR adds support for this button, and updates the SteamController to add support for `STEAM` button.
**NOTE** this PR does *not* require Xcode 12, or iOS 14.
**NOTE** the `STEAM` button on the SteamController will work even on iOS 13, Xbox and DualShock will require iOS 14.
> iOS 14 Game Controller MENU button support.

- iOS/CGScreenView.m
- iOS/EmulatorController.m
- iOS/MetalScreenView.m
- xcode/MAME4iOS/ChooseGameController.m
- xcode/MAME4iOS/CloudSync.m
- xcode/MAME4iOS/ColorSpace.m
- xcode/MAME4iOS/ImageCache.m
- xcode/MAME4iOS/InfoHUD.m
- xcode/MAME4iOS/MetalView.m
- xcode/MAME4iOS/SkinManager.m
- xcode/MAME4iOS/Widget/Widget.swift
AltStore (and maybe others) when sideloading will add TEAM ident to the end of our bundle identifier
change the code to handle bundle identifiers with more than three components correctly.
> fix AltStore sideloading crash.

- iOS/MetalScreenView.m
- src/osd/droid-ios/myosd.h
Use the texture UVs computed by MAME, don't try to make our own.
> Draw rotated or flipped textured QUADs correctly

- iOS/EmulatorController.m
- src/emu/uimenu.c
- src/osd/droid-ios/libmame.h
- src/osd/droid-ios/myosd.h
- src/osd/droid-ios/osd-ios.c
- src/osd/droid-ios/osdinput.c
pass more info up to app in myosd_game_info
* game type (arcade, console, computer, other)
* game flags (IS_BIOS, VERTICAL, NOT_WORKING, IMPERFECT_GRAPHICS, ...)
this is a change to match current `MAME`
> change how OSD passes the game_list to app.

- iOS/EmulatorController.m
- iOS/Globals.h
- src/emu/ui.c
- src/emu/uimenu.c
- src/osd/droid-ios/libmame.h
- src/osd/droid-ios/myosd.h
- src/osd/droid-ios/osd-ios.c
- src/osd/droid-ios/osdinput.c
- src/osd/droid-ios/osdmain.c
- src/osd/droid-ios/osdvideo.c
* remove OSD globals `myosd_inGame` and `myosd_in_menu`
* added `video_exit`, `input_init`, `input_exit` host callbacks.
* added `game_init`, and `game_exit` callbacks for current machine.
* added `input_mode` and `keyboard_mode` to `myosd_input_state`
> Modern mame

- iOS/EmulatorController.m
- iOS/OptionsController.m
- xcode/MAME4iOS/Options.h
- xcode/MAME4iOS/Options.m
- xcode/MAME4iOS/TVOptionsController.m
Put the Sound Settings options back, it was removed in the `OSD` purge.
different command line options are needed for 139 vs 2xx, but this handles that now.
> Sound Settings are back.

- make-mac.sh
- makefile
- xcode/MAME4iOS/Classic.xcconfig
- xcode/MAME4iOS/MAME4iOS.xcconfig
- xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
- Added MAMELIB_* defines in the main xcconfig
- Added a Classic.xcconfig for building the classic version of the app
- Changed the project.pbxproj to use the MAMELIB_* variables
- Added the Classic schemes to the project so you can build the classic versions
> Support building app binary for 0.139 (Classic) and Latest MAME

- README.md
- WHATSNEW.md
- iOS-res/help.md
- iOS/Bootstrapper.m
- iOS/EmulatorController.h
- iOS/EmulatorController.m
- iOS/KeyboardView.m
- iOS/OptionsController.m
- iOS/OptionsTableViewController.m
- src/osd/droid-ios/libmame.h
- src/osd/droid-ios/osdinput.c
- xcode/MAME4iOS/ChooseGameController.m
- xcode/MAME4iOS/MAME4iOS.xcodeproj/project.pbxproj
- xcode/MAME4iOS/MAME4iOS/MAME4iOS-Info.plist
- xcode/MAME4iOS/MAME4mac/MAME4mac-Info.plist
- xcode/MAME4iOS/MacMenu.m
- xcode/MAME4iOS/SoftwareList.h
- xcode/MAME4iOS/SoftwareList.m
- xcode/MAME4iOS/ZipFile.m
* Handle full built in Software Lists from MAME (as HASH.ZIP)
* Don't import XML files anymore, not needed.
* Search for correct software list for a ROMSET by comparing SHA1 *not* the file names
* handle iOS 15 and iPad CMD+. keyboard shortcut.
* Added Menu (and button in Settings) to open Document directory in `Files.app` (or `Finder.app`)
> MAME update

- iOS/EmulatorController.m
Small change to hide the touch controls (d-pad, buttons) when the software keyboard is enabled
> Hide touch controls when software keyboard is enabled

- WHATSNEW.md
- iOS/EmulatorController.m
use the entire screen (ignore safe area) if `Keep Aspect Ratio` is `OFF`
> Full Fullscreen

- xcode/MAME4iOS/ChooseGameController.m
- xcode/MAME4iOS/PopupSegmentedControl.h
- xcode/MAME4iOS/PopupSegmentedControl.m
have PopupSegmentedControl use an UIAlertViewController on tvOS to let user choose an option.
the Segmented Control used to grow and shrink when it got the focus, now it always stays the same size and shows an Alert when it is selected.
> Change PopupSegmentedController on tvOS

- iOS/EmulatorController.m
- xcode/MAME4iOS/GCDWebUploader/GCDWebUploader.h
- xcode/MAME4iOS/GCDWebUploader/GCDWebUploader.m
feedback is already shown in the browser, this adds it to the UX on device.
> Show Server upload feedback on the device.
